# Generated by Django 5.0.1 on 2024-01-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('especiality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('idDoctor', models.ManyToManyField(to='myapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='medicalCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('age', models.CharField(max_length=100)),
                ('idConsultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.consultation')),
            ],
        ),
    ]
