# Generated by Django 5.0.1 on 2024-02-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='idDoctor',
        ),
        migrations.RemoveField(
            model_name='medicalcenter',
            name='idDoctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='idmedicalCenter',
            field=models.ManyToManyField(to='myapp.medicalcenter'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='idDoctor',
            field=models.ManyToManyField(to='myapp.doctor'),
        ),
    ]
